server:
  port: 8091

management:
  security:
    enabled: false

spring:
  application:
    name: daasWeatherService
  datasource:
    url: jdbc:postgresql://localhost:5432/weather?currentSchema=weather
    username: eos
    password:
    type: com.zaxxer.hikari.HikariDataSource
    validationQuery: SELECT 1
    hikari:
      maximum-pool-size: 5
      idle-timeout: 10000
      minimum-idle: 1
      connection-test-query: SELECT 1
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: false
    hibernate:
      ddl-auto: none
    show-sql: true
    properties.hibernate.generate_statistics: true

flyway:
  baselineOnMigrate: true

